// Auto-generated by crap-cms. Do not edit.

use serde::{Deserialize, Serialize};

/// A relationship field: either an ID string (depth=0)
/// or a populated document (depth>=1).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Rel<T> {
    Doc(Box<T>),
    Id(String),
}

impl<T> Rel<T> {
    /// Get the ID if unpopulated.
    pub fn as_id(&self) -> Option<&str> {
        match self { Rel::Id(id) => Some(id), _ => None }
    }

    /// Get the populated document.
    pub fn as_doc(&self) -> Option<&T> {
        match self { Rel::Doc(d) => Some(d), _ => None }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Categories {
    pub id: String,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Comments {
    pub id: String,
    pub body: String,
    pub author: Rel<Users>,
    pub task: Rel<Tasks>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Media {
    pub id: String,
    pub filename: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub filesize: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub height: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub focal_x: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub focal_y: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thumbnail_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thumbnail_width: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thumbnail_height: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alt: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TasksSubtasks {
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub done: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Tasks {
    pub id: String,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub status: String,
    pub priority: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub due_date: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub overdue: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub assignee: Option<Rel<Users>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<Rel<Categories>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<Rel<Media>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subtasks: Option<Vec<TasksSubtasks>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Users {
    pub id: String,
    pub email: String,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub avatar: Option<Rel<Media>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bio: Option<String>,
    pub role: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppSettings {
    pub id: String,
    pub app_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tagline: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub motd: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

