// Auto-generated by crap-cms. Do not edit.
//
// Proto-to-struct conversion for prost_types.
// Import the generated structs from generated.rs alongside this file.
use prost_types::value::Kind;
use crate::grpc::proto::Document;

use super::generated::*;

/// Trait for types that can be constructed from a proto Document.
pub trait FromDocument {
    fn from_document(doc: &Document) -> Self;
}

// ── Extraction helpers ─────────────────────────────────────

fn get_str(doc: &Document, name: &str) -> String {
    doc.fields.as_ref()
        .and_then(|f| f.fields.get(name))
        .and_then(|v| match &v.kind {
            Some(Kind::StringValue(s)) => Some(s.clone()),
            _ => None,
        })
        .unwrap_or_default()
}

fn get_str_opt(doc: &Document, name: &str) -> Option<String> {
    let s = get_str(doc, name);
    if s.is_empty() { None } else { Some(s) }
}

fn get_num(doc: &Document, name: &str) -> f64 {
    doc.fields.as_ref()
        .and_then(|f| f.fields.get(name))
        .and_then(|v| match &v.kind {
            Some(Kind::NumberValue(n)) => Some(*n),
            _ => None,
        })
        .unwrap_or(0.0)
}

fn get_num_opt(doc: &Document, name: &str) -> Option<f64> {
    doc.fields.as_ref()
        .and_then(|f| f.fields.get(name))
        .and_then(|v| match &v.kind {
            Some(Kind::NumberValue(n)) => Some(*n),
            _ => None,
        })
}

fn get_bool(doc: &Document, name: &str) -> bool {
    doc.fields.as_ref()
        .and_then(|f| f.fields.get(name))
        .and_then(|v| match &v.kind {
            Some(Kind::BoolValue(b)) => Some(*b),
            _ => None,
        })
        .unwrap_or(false)
}

fn get_bool_opt(doc: &Document, name: &str) -> Option<bool> {
    doc.fields.as_ref()
        .and_then(|f| f.fields.get(name))
        .and_then(|v| match &v.kind {
            Some(Kind::BoolValue(b)) => Some(*b),
            _ => None,
        })
}

fn get_str_list(doc: &Document, name: &str) -> Vec<String> {
    doc.fields.as_ref()
        .and_then(|f| f.fields.get(name))
        .and_then(|v| match &v.kind {
            Some(Kind::ListValue(list)) => Some(
                list.values.iter()
                    .filter_map(|v| match &v.kind {
                        Some(Kind::StringValue(s)) => Some(s.clone()),
                        _ => None,
                    })
                    .collect()
            ),
            _ => None,
        })
        .unwrap_or_default()
}

// ── Relationship helpers ──────────────────────────────────

fn struct_to_document(s: &prost_types::Struct) -> Document {
    let id = s.fields.get("id")
        .and_then(|v| match &v.kind {
            Some(Kind::StringValue(s)) => Some(s.clone()),
            _ => None,
        })
        .unwrap_or_default();

    Document {
        id,
        collection: String::new(),
        fields: Some(prost_types::Struct { fields: s.fields.clone() }),
        created_at: s.fields.get("created_at").and_then(|v| match &v.kind {
            Some(Kind::StringValue(s)) => Some(s.clone()),
            _ => None,
        }),
        updated_at: s.fields.get("updated_at").and_then(|v| match &v.kind {
            Some(Kind::StringValue(s)) => Some(s.clone()),
            _ => None,
        }),
    }
}

fn get_rel<T: FromDocument>(doc: &Document, name: &str) -> Option<Rel<T>> {
    doc.fields.as_ref()
        .and_then(|f| f.fields.get(name))
        .and_then(|v| match &v.kind {
            Some(Kind::StringValue(s)) if !s.is_empty() => Some(Rel::Id(s.clone())),
            Some(Kind::StructValue(s)) => {
                let inner = struct_to_document(s);
                Some(Rel::Doc(Box::new(T::from_document(&inner))))
            }
            _ => None,
        })
}

fn get_rel_list<T: FromDocument>(doc: &Document, name: &str) -> Vec<Rel<T>> {
    doc.fields.as_ref()
        .and_then(|f| f.fields.get(name))
        .and_then(|v| match &v.kind {
            Some(Kind::ListValue(list)) => Some(
                list.values.iter()
                    .filter_map(|v| match &v.kind {
                        Some(Kind::StringValue(s)) if !s.is_empty() => Some(Rel::Id(s.clone())),
                        Some(Kind::StructValue(s)) => {
                            let inner = struct_to_document(s);
                            Some(Rel::Doc(Box::new(T::from_document(&inner))))
                        }
                        _ => None,
                    })
                    .collect()
            ),
            _ => None,
        })
        .unwrap_or_default()
}

impl Categories {
    pub fn from_document(doc: &Document) -> Self {
        Self {
            id: doc.id.clone(),
            name: get_str(doc, "name"),
            color: get_str_opt(doc, "color"),
            icon: get_str_opt(doc, "icon"),
            created_at: doc.created_at.clone(),
            updated_at: doc.updated_at.clone(),
        }
    }
}

impl FromDocument for Categories {
    fn from_document(doc: &Document) -> Self {
        Categories::from_document(doc)
    }
}

impl Comments {
    pub fn from_document(doc: &Document) -> Self {
        Self {
            id: doc.id.clone(),
            body: get_str(doc, "body"),
            author: get_rel(doc, "author").unwrap_or(Rel::Id(String::new())),
            task: get_rel(doc, "task").unwrap_or(Rel::Id(String::new())),
            created_at: doc.created_at.clone(),
            updated_at: doc.updated_at.clone(),
        }
    }
}

impl FromDocument for Comments {
    fn from_document(doc: &Document) -> Self {
        Comments::from_document(doc)
    }
}

impl Media {
    pub fn from_document(doc: &Document) -> Self {
        Self {
            id: doc.id.clone(),
            filename: get_str(doc, "filename"),
            mime_type: get_str_opt(doc, "mime_type"),
            filesize: get_num_opt(doc, "filesize"),
            width: get_num_opt(doc, "width"),
            height: get_num_opt(doc, "height"),
            url: get_str_opt(doc, "url"),
            focal_x: get_num_opt(doc, "focal_x"),
            focal_y: get_num_opt(doc, "focal_y"),
            thumbnail_url: get_str_opt(doc, "thumbnail_url"),
            thumbnail_width: get_num_opt(doc, "thumbnail_width"),
            thumbnail_height: get_num_opt(doc, "thumbnail_height"),
            alt: get_str_opt(doc, "alt"),
            created_at: doc.created_at.clone(),
            updated_at: doc.updated_at.clone(),
        }
    }
}

impl FromDocument for Media {
    fn from_document(doc: &Document) -> Self {
        Media::from_document(doc)
    }
}

impl TasksSubtasks {
    fn from_struct(s: &prost_types::Struct) -> Self {
        Self {
            title: s.fields.get("title").and_then(|v| match &v.kind { Some(Kind::StringValue(s)) => Some(s.clone()), _ => None }).unwrap_or_default(),
            done: s.fields.get("done").and_then(|v| match &v.kind { Some(Kind::BoolValue(b)) => Some(*b), _ => None }),
        }
    }
}

impl Tasks {
    pub fn from_document(doc: &Document) -> Self {
        Self {
            id: doc.id.clone(),
            title: get_str(doc, "title"),
            slug: get_str_opt(doc, "slug"),
            description: get_str_opt(doc, "description"),
            status: get_str(doc, "status"),
            priority: get_num(doc, "priority"),
            due_date: get_str_opt(doc, "due_date"),
            overdue: get_bool_opt(doc, "overdue"),
            assignee: get_rel(doc, "assignee"),
            category: get_rel(doc, "category"),
            attachments: { let v = get_rel_list(doc, "attachments"); if v.is_empty() { None } else { Some(v) } },
            subtasks: doc.fields.as_ref().and_then(|f| f.fields.get("subtasks")).and_then(|v| match &v.kind {Some(Kind::ListValue(list)) => Some(list.values.iter().filter_map(|v| match &v.kind {Some(Kind::StructValue(s)) => Some(TasksSubtasks::from_struct(s)),_ => None,}).collect::<Vec<_>>()),_ => None,}),
            created_at: doc.created_at.clone(),
            updated_at: doc.updated_at.clone(),
        }
    }
}

impl FromDocument for Tasks {
    fn from_document(doc: &Document) -> Self {
        Tasks::from_document(doc)
    }
}

impl Users {
    pub fn from_document(doc: &Document) -> Self {
        Self {
            id: doc.id.clone(),
            email: get_str(doc, "email"),
            name: get_str(doc, "name"),
            avatar: get_rel(doc, "avatar"),
            bio: get_str_opt(doc, "bio"),
            role: get_str(doc, "role"),
            created_at: doc.created_at.clone(),
            updated_at: doc.updated_at.clone(),
        }
    }
}

impl FromDocument for Users {
    fn from_document(doc: &Document) -> Self {
        Users::from_document(doc)
    }
}

impl AppSettings {
    pub fn from_document(doc: &Document) -> Self {
        Self {
            id: doc.id.clone(),
            app_name: get_str(doc, "app_name"),
            tagline: get_str_opt(doc, "tagline"),
            motd: get_str_opt(doc, "motd"),
            created_at: doc.created_at.clone(),
            updated_at: doc.updated_at.clone(),
        }
    }
}

impl FromDocument for AppSettings {
    fn from_document(doc: &Document) -> Self {
        AppSettings::from_document(doc)
    }
}

